version: "3"
services:
  frontend:
    build:
      context:
        ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/frontend
      - /frontend/node_modules
    links:
      - backend
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/src/app/backend
      - /backend/node_modules

